apiVersion: v1
kind: Service
metadata:
  name: lab-service
spec:
  type: NodePort
  selector:
    app: app-k8s                  # Conecta con pods que tengan esta etiqueta
  ports:
    - port: 80                      # Puerto del Service
      targetPort: 8080              # Puerto del contenedor
      nodePort: 30080               # Puerto en localhost